# Generated by Django 4.1.5 on 2023-01-30 02:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название рассылки')),
                ('periodicity', models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Ежедневно', max_length=20, verbose_name='Периодичность')),
                ('mail_dump', models.FileField(blank=True, null=True, upload_to='maildumps/1/', verbose_name='База рассылки в формате .txt')),
                ('status', models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=20, verbose_name='Статус')),
                ('cron_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Период задачи')),
                ('cron_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='Путь задачи')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=2, null=True, verbose_name='Час рассылки')),
            ],
            options={
                'verbose_name': 'час',
                'verbose_name_plural': 'часы',
            },
        ),
        migrations.CreateModel(
            name='LetterMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание письма')),
                ('position', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000000)], verbose_name='Очередь на отправку')),
                ('status', models.CharField(choices=[('Отправлено', 'Отправлено'), ('Ожидает отправки', 'Ожидает отправки')], default='Ожидает отправки', max_length=20, verbose_name='Статус отправки')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.configmailing', verbose_name='Рассылка')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин клиента')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=2, verbose_name='Минуты рассылки')),
            ],
            options={
                'verbose_name': 'минута',
                'verbose_name_plural': 'минуты',
            },
        ),
        migrations.CreateModel(
            name='MonthDate',
            fields=[
                ('number', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Дата месяца')),
            ],
            options={
                'verbose_name': 'число месяца',
                'verbose_name_plural': 'числа месяца',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, unique=True, verbose_name='День недели')),
                ('day_id', models.SmallIntegerField(blank=True, null=True, verbose_name='Идентификатор дня')),
            ],
            options={
                'verbose_name': 'день недели',
                'verbose_name_plural': 'дни недели',
            },
        ),
        migrations.CreateModel(
            name='TryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_try', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки')),
                ('mail_server_respond', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ почтового сервера')),
                ('count_try', models.SmallIntegerField(default=0, verbose_name='Количество попыток')),
                ('letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sender.lettermailing', verbose_name='Отправленное письмо')),
                ('mailing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sender.configmailing', verbose_name='Рассылка')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин клиента')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
        migrations.AddField(
            model_name='configmailing',
            name='hour',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='sender.hour', verbose_name='Час рассылки'),
        ),
        migrations.AddField(
            model_name='configmailing',
            name='minute',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sender.minute', verbose_name='Минуты'),
        ),
        migrations.AddField(
            model_name='configmailing',
            name='monthdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sender.monthdate', verbose_name='Дата месяца'),
        ),
        migrations.AddField(
            model_name='configmailing',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин клиента'),
        ),
        migrations.AddField(
            model_name='configmailing',
            name='weekday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sender.weekday', verbose_name='День недели'),
        ),
    ]
